import os
from pathlib import Path
from collections import defaultdict

staging_dir = Path("data/skills_staging")
master_file = Path("data/V2_MASTER_CONTEXT.md")

architect_counts = defaultdict(int)
architect_largest = {}

files = list(staging_dir.glob("*.md"))
files.sort(key=lambda x: x.stat().st_size, reverse=True)

total_files = 0
with open(master_file, "w") as out:
    out.write("# V2 MASTER CONTEXT\n\nThis document contains the fully synthesized architectural history of the Odysseus system, generated by the 11-agent background fleet.\n\n")
    
    for f in files:
        if f.name == "v2_blueprint_critique.md" or f.name == "auto_apply_job_architect.md":
            continue
            
        size = f.stat().st_size
        if size <= 1: # Ignore 0B and 1B files (like ".")
            continue
            
        total_files += 1
        
        # Parse architect name
        name_parts = f.name.split("_")
        if len(name_parts) >= 2:
            arch_name = name_parts[1]
            architect_counts[arch_name] += 1
            if arch_name not in architect_largest:
                architect_largest[arch_name] = (f.name, size)
                
        out.write("\n\n" + "="*80 + "\n")
        out.write(f"## FILE: {f.name}\n")
        out.write("="*80 + "\n\n")
        out.write(f.read_text())

print(f"Total valid non-zero files: {total_files}")
for arch, count in architect_counts.items():
    largest_file, largest_size = architect_largest[arch]
    print(f"{arch}: {count} files (Largest: {largest_size/1024:.1f} KB)")
